taxi/urls.py
from django.urls import path

from .views import (
    index,
    CarListView,
    CarDetailView,
    DriverListView,
    DriverDetailView,
    ManufacturerListView,
    CarCreateView,
    CarUpdateView,
    CarDeleteView,
    ManufacturerUpdateView,
    ManufacturerDeleteView,
    ManufacturerCreateView,
    DriverCreateView,
    DriverUpdateView,
    DriverDeleteView,
    register_request,
)

urlpatterns = [
    path("", index, name="index"),
    path("manufacturers/", ManufacturerListView.as_view(), name="manufacturer-list"),
    path("cars/", CarListView.as_view(), name="car-list"),
    path("cars/<int:pk>/", CarDetailView.as_view(), name="car-detail"),
    path("drivers/", DriverListView.as_view(), name="driver-list"),
    path("drivers/<int:pk>/", DriverDetailView.as_view(), name="driver-detail"),
    path("create-car/", CarCreateView.as_view(), name="create-car"),
    path("cars/<int:pk>/update/", CarUpdateView.as_view(), name="car-update"),
    path("cars/<int:pk>/delete/", CarDeleteView.as_view(), name="car-delete"),
    path(
        "manufacturers/<int:pk>/update/",
        ManufacturerUpdateView.as_view(),
        name="manufacturer-update",
    ),
    path(
        "manufacturers/<int:pk>/delete/",
        ManufacturerDeleteView.as_view(),
        name="manufacturer-delete",
    ),
    path(
        "manufacturers/create/",
        ManufacturerCreateView.as_view(),
        name="create-manufacturer",
    ),
    path("drivers/create/", DriverCreateView.as_view(), name="create-driver"),
    path("drivers/<int:pk>/update/", DriverUpdateView.as_view(), name="driver-update"),
    path("drivers/<int:pk>/delete", DriverDeleteView.as_view(), name="driver-delete"),
    path("register/", register_request, name="register"),
]

app_name = "taxi"

taxi_service/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static


urlpatterns = [
    path("admin/", admin.site.urls),
    path("", include("taxi.urls", namespace="taxi")),
    path("accounts/", include("django.contrib.auth.urls")),
] + static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

taxi/models.py
from django.db import models
from django.contrib.auth.models import AbstractUser
from django.urls import reverse


class Manufacturer(models.Model):
    name = models.CharField(max_length=255)
    country = models.CharField(max_length=255)

    class Meta:
        ordering = ["name"]

    def __str__(self):
        return f"{self.name} {self.country}"


class Driver(AbstractUser):
    license_number = models.CharField(max_length=8, unique=True)

    class Meta:
        verbose_name = "driver"
        verbose_name_plural = "drivers"

    def __str__(self):
        return f"{self.username} {self.first_name} {self.last_name}"

    def get_absolute_url(self):
        return reverse("taxi:driver-detail", kwargs={"pk": self.pk})


class Car(models.Model):
    model = models.CharField(max_length=255)
    manufacturer = models.ForeignKey(Manufacturer, on_delete=models.CASCADE)
    drivers = models.ManyToManyField(Driver, related_name="cars")

    def __str__(self):
        return self.model

taxi/forms.py
from django import forms
from django.contrib.auth import get_user_model
from django.core.exceptions import ValidationError
from django.contrib.auth.forms import UserCreationForm
from django.contrib.auth.models import User

from taxi.models import Driver


class DriverForm(forms.ModelForm):
    class Meta:
        model = Driver
        fields = ("username", "first_name", "last_name", "license_number")

    def clean_license_number(self):
        license_number = self.cleaned_data["license_number"]

        if len(license_number) != 8:
            raise ValidationError("License number must be 8 characters long")
        if not license_number[:3].isalpha() or not license_number[:3].isupper():
            raise ValidationError("License number must start with 3 upper case letters")
        if not license_number[3:].isdigit():
            raise ValidationError("License number must end with 5 digits only")
        return license_number


class CarSearchForm(forms.Form):
    model = forms.CharField(
        max_length=255,
        required=False,
        label="",
        widget=forms.TextInput(attrs={"placeholder": "Search car by model"}),
    )


class NewUserForm(UserCreationForm):
    email = forms.EmailField(required=False)

    class Meta:
        model = get_user_model()
        fields = ("username", "license_number", "password1", "password2")

    def save(self, commit=True):
        user = super(NewUserForm, self).save(commit=False)
        user.email = self.cleaned_data["email"]
        if commit:
            user.save()
        return user

taxi/views.py
from django.contrib import messages
from django.contrib.auth import login
from django.contrib.auth.decorators import login_required
from django.shortcuts import render, redirect
from django.urls import reverse_lazy
from django.views import generic
from django.contrib.auth.mixins import LoginRequiredMixin

from .forms import DriverForm, CarSearchForm, NewUserForm
from .models import Driver, Car, Manufacturer


@login_required
def index(request):
    """View function for the home page of the site."""

    num_drivers = Driver.objects.count()
    num_cars = Car.objects.count()
    num_manufacturers = Manufacturer.objects.count()

    num_visits = request.session.get("num_visits", 0)
    request.session["num_visits"] = num_visits + 1

    context = {
        "num_drivers": num_drivers,
        "num_cars": num_cars,
        "num_manufacturers": num_manufacturers,
        "num_visits": num_visits,
    }

    return render(request, "taxi/index.html", context=context)


class ManufacturerListView(LoginRequiredMixin, generic.ListView):
    model = Manufacturer
    context_object_name = "manufacturer_list"
    template_name = "taxi/manufacturer_list.html"
    paginate_by = 5


class CarListView(LoginRequiredMixin, generic.ListView):
    model = Car
    paginate_by = 5
    queryset = Car.objects.all().select_related("manufacturer")

    def get_context_data(self, *, object_list=None, **kwargs):
        context = super(CarListView, self).get_context_data(**kwargs)
        model = self.request.GET.get("model", "")
        context["search_form"] = CarSearchForm(initial={"model": model})

        return context

    def get_queryset(self):
        form = CarSearchForm(self.request.GET)

        if form.is_valid():
            return self.queryset.filter(model__icontains=form.cleaned_data["model"])
        return self.queryset


class CarDetailView(LoginRequiredMixin, generic.DetailView):
    model = Car


class CarCreateView(LoginRequiredMixin, generic.CreateView):
    model = Car
    fields = ["manufacturer", "model", "drivers"]
    success_url = reverse_lazy("taxi:car-list")


class CarUpdateView(LoginRequiredMixin, generic.UpdateView):
    model = Car
    fields = ["manufacturer", "model", "drivers"]
    success_url = reverse_lazy("taxi:car-list")
    template_name = "taxi/car_form.html"


class CarDeleteView(LoginRequiredMixin, generic.DeleteView):
    model = Car
    fields = "__all__"
    success_url = reverse_lazy("taxi:car-list")
    template_name = "taxi/car_delete.html"


class DriverListView(LoginRequiredMixin, generic.ListView):
    model = Driver
    paginate_by = 5


class DriverDetailView(LoginRequiredMixin, generic.DetailView):
    model = Driver
    queryset = Driver.objects.all().prefetch_related("cars__manufacturer")


class ManufacturerCreateView(LoginRequiredMixin, generic.CreateView):
    model = Manufacturer
    fields = ["name", "country"]
    success_url = reverse_lazy("taxi:manufacturer-list")


class ManufacturerUpdateView(LoginRequiredMixin, generic.UpdateView):
    model = Manufacturer
    fields = ["name", "country"]
    success_url = reverse_lazy("taxi:manufacturer-list")
    template_name = "taxi/manufacturer_form.html"


class ManufacturerDeleteView(LoginRequiredMixin, generic.DeleteView):
    model = Manufacturer
    fields = "__all__"
    success_url = reverse_lazy("taxi:manufacturer-list")
    template_name = "taxi/manufacturer_delete.html"


class DriverCreateView(LoginRequiredMixin, generic.CreateView):
    model = Driver
    form_class = DriverForm
    success_url = reverse_lazy("taxi:driver-list")


class DriverUpdateView(LoginRequiredMixin, generic.UpdateView):
    model = Driver
    form_class = DriverForm
    success_url = reverse_lazy("taxi:driver-list")
    template_name = "taxi/driver_form.html"


class DriverDeleteView(LoginRequiredMixin, generic.DeleteView):
    model = Driver
    fields = "__all__"
    success_url = reverse_lazy("taxi:driver-list")
    template_name = "taxi/driver_delete.html"


def register_request(request):
    if request.method == "POST":
        form = NewUserForm(request.POST)
        if form.is_valid():
            user = form.save()
            login(request, user)
            messages.success(request, "Registration successful!")
            return redirect("taxi:index")
        messages.error(request, "Unsuccessful registration. Invalid registration")
    form = NewUserForm()
    return render(
        request=request,
        template_name="registration/register.html",
        context={"register_form": form},
    )

templates/taxi/car_delete.html
{% extends "base.html" %}

{% block content %}
  <h1>Delete Car</h1>

  <p>Are you sure you want to remove this car?</p>

  <form action="" method="post" novalidate>
    {% csrf_token %}
    <input type="submit" class="btn btn-danger" value="Delete">
  </form>
{% endblock %}

templates/taxi/car_detail.html
{% extends "base.html" %}

{% block content %}
  <h1 style="margin-top: 20px">Manufacturer:</h1>
  <h4>{{ car.manufacturer.name }}, {{ car.manufacturer.country }}</h4>
  <a href="{% url 'taxi:car-update' pk=car.id %}" class="btn btn-primary" style="float:right">Update</a>
  <br>
  <br>
  <a href="{% url 'taxi:car-delete' pk=car.id %}" class="btn btn-danger" style="float:right">Delete</a>
  <h1>Drivers</h1>
  <table class="table table-bordered table-striped">
  <tr>
    <th>Username</th>
    <th>First name</th>
    <th>Last name</th>
  </tr>

  {% for driver in car.drivers.all %}
    <tr>
      <td>{{ driver.username }}</td>
      <td>{{ driver.first_name }}</td>
      <td>{{ driver.last_name }}</td>
    </tr>
  {% endfor %}
{% endblock %}

templates/taxi/car_form.html
{% extends "base.html" %}
{% load crispy_forms_filters %}

{% block content %}
  <h1>{{ object|yesno:"Update,Create" }} car</h1>
  <form action="" method="post" class="form-horizontal">
    {% csrf_token %}
    {{ form|crispy }}
    <input class="btn btn-primary" type="submit" value="Submit">
  </form>
{% endblock %}

templates/taxi/car_list.html
{% extends "base.html" %}
{% load crispy_forms_filters %}

{% block content %}
  <h1>Car list</h1>
  <a href="{% url 'taxi:create-car' %}" class="btn btn-primary" style="float:right">Add new car</a>

  <form action="" method="get" class="form-inline">
    {{ search_form|crispy }}
    <input type="submit" value="Search car" class="btn btn-primary">
  </form>
  <br>

  {% if car_list %}
    <table class="table table-bordered table-striped">
      <tr>
        <th>ID</th>
        <th>Manufacturer</th>
        <th>Model</th>
      </tr>
      {% for car in car_list %}
        <tr>
          <td>{{ car.id }}</td>
          <td>{{ car.manufacturer }}</td>
          <td><a href="{% url 'taxi:car-detail' pk=car.id %}">{{ car.model }}</a></td>
        </tr>
      {% endfor %}
    </table>

  {% else %}
    <p>There are no cars in taxi</p>
  {% endif %}
{% endblock %}

templates/taxi/driver_delete.html
{% extends "base.html"%}

{% block content %}
    <h1>Delete Driver</h1>

    <p>Are you sure you want to remove this driver?</p>

    <form action="" method="post" novalidate>
    {% csrf_token %}
        <input type="submit" class="btn btn-danger" value="Delete">
    </form>
{% endblock %}

templates/taxi/driver_detail.html
{% extends "base.html" %}

{% block content %}
  <h1 style="margin-top: 20px">
    Username: {{ driver.username }}
    <a href="{% url 'taxi:driver-update' pk=driver.id %}" class="btn btn-primary" style="float:right"
    >Update</a>
    <br>
    <a href="{% url 'taxi:driver-delete' pk=driver.id %}" class="btn btn-danger" style="float:right">Delete</a>
  </h1>

  <p><strong>First name:</strong> {{ driver.first_name }}</p>
  <p><strong>Last name:</strong> {{ driver.last_name }}</p>
  <p><strong>License number:</strong> {{ driver.license_number }}</p>
  <p><strong>Is staff:</strong> {{ driver.is_staff }}</p>

  <div class="ml-3">
    <h4>Cars</h4>

    {% for car in driver.cars.all %}
      <hr>
      <p><strong>Model:</strong> {{ car.model }}</p>
      <p><strong>Manufacturer:</strong> {{ car.manufacturer.name }}</p>
      <p class="text-muted"><strong>Id:</strong> {{ car.id }}</p>

    {% empty %}
      <p>No cars!</p>
    {% endfor %}
  </div>
{% endblock %}

templates/taxi/driver_form.html
{% extends "base.html" %}
{% load crispy_forms_filters %}

{% block content %}
  <h1>{{ object|yesno:"Update,Create" }} driver</h1>
  <form action="" method="post" class="form-horizontal">
    {% csrf_token %}
    {{ form|crispy }}
    <input class="btn btn-primary" type="submit" value="Submit">
  </form>
{% endblock %}

templates/taxi/driver_list.html
{% extends "base.html" %}
{% load crispy_forms_filters %}

{% block content %}
  <h1 style="margin-top: 20px">Driver List
  </h1>
  <a href="{% url 'taxi:create-driver' %}" class="btn btn-primary" style="float:right">Add new driver</a>

  <p>


    {% if driver_list %}

      <table class="table table-bordered table-striped" style="margin-top: 75px">
        <tr>
          <th>ID</th>
          <th>Username</th>
          <th>First name</th>
          <th>Last name</th>
          <th>License number</th>
        </tr>
        {% for driver in driver_list %}
          <tr>
            <td>{{ driver.id }}</td>
            <td><a href="{{ driver.get_absolute_url }}">{{ driver.username }} {% if user == driver %}
              (Me){% endif %}</a></td>
            <td>{{ driver.first_name }}</td>
            <td>{{ driver.last_name }}</td>
            <td>{{ driver.license_number }}</td>
          </tr>
        {% endfor %}

      </table>
    {% else %}
      <p>There are no drivers in the service.</p>
    {% endif %}
  </p>
{% endblock %}

templates/taxi/index.html
{% extends "base.html" %}

{% block content %}
  <h1>Taxi Service Home</h1>
  <p>Welcome to Best Taxi Ever!</p>
  <h2>Dynamic content</h2>
  <p>The Taxi service has the following record counts:</p>
  <ul>
    <li><strong>Cars:</strong> {{ num_cars }}</li>
    <li><strong>Drivers:</strong> {{ num_drivers }}</li>
    <li><strong>Manufacturers:</strong> {{ num_manufacturers }}</li>
  </ul>

  <p>You have visited this page
    {{ num_visits }} time{{ num_visits|pluralize }}.
  </p>

{% endblock %}

templates/taxi/manufacturer_delete.html
{% extends "base.html" %}

{% block content %}
  <h1>Delete Manufacturer</h1>

  <p>Are you sure you want to remove this manufacturer?</p>

  <form action="" method="post" novalidate>
    {% csrf_token %}
    <input type="submit" class="btn btn-danger" value="Delete">
  </form>
{% endblock %}

templates/taxi/manufacturer_form.html
{% extends "base.html" %}
{% load crispy_forms_filters %}

{% block content %}
  <h1>{{ object|yesno:"Update,Create" }} manufacturer</h1>
  <form action="" method="post" class="form-horizontal">
    {% csrf_token %}
    {{ form|crispy }}
    <input class="btn btn-primary" type="submit" value="Submit">
  </form>
{% endblock %}

templates/taxi/manufacturer_list.html
{% extends "base.html" %}

{% block content %}
  <h1 style="margin-top: 20px;">Manufacturer List</h1>
  <a href="{% url 'taxi:create-manufacturer' %}" class="btn btn-primary" style="float:right">Add new manufacturer</a>


  {% if manufacturer_list %}
    <table class="table table-bordered table-striped" style="margin-top: 75px">
      <tr>
        <th>ID</th>
        <th>Name</th>
        <th>Country</th>
        <th>Update</th>
        <th>Delete</th>
      </tr>

      {% for manufacturer in manufacturer_list %}
        <tr>
          <td>
            {{ manufacturer.id }}
          </td>
          <td>
            {{ manufacturer.name }}
          </td>
          <td>
            {{ manufacturer.country }}
          </td>
          <td>
            <a href="{% url 'taxi:manufacturer-update' pk=manufacturer.id %}" class="btn btn-primary">Update</a>
          </td>
          <td>
            <a href="{% url 'taxi:manufacturer-delete' pk=manufacturer.id %}" class="btn btn-danger">Delete</a>
          </td>
        </tr>
      {% endfor %}
    </table>

  {% else %}
    <p>There are no manufacturers in the service.</p>
  {% endif %}
{% endblock %}